### ISSUE TITLE
Add compile optimizations

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_server#24]
@deajan 
You have added this:

https://github.com/grke/burp/wiki/Performance-Tips#optional-compile-time-improvements

When compiling burp, you can optimize it for your actual processor architecture, and add a certain degree of parallelism that will give a little performance improvement (expect 5%).
Add the following CFLAGS to your configure statement

```CFLAGS="-O2 -march=native -mtune=native -mfpmath=sse -floop-parallelize-all -ftree-parallelize-loops=4" ./configure```

Be aware that using -march and -mtune will make your compiled burp work only with the actual processor you compiled with. Omit those parameters if you want to compile for other cpus.

This role compliles burp so I think it could help on default compilation.

What do you think?
Should I add these compile commands to the role?

**Comment by deajan** [comment]
As long as you compile burp on each host, you're fine with -march and -mtune.
If you happen to compile a central burp and distribute it, leave those both options out.
The other options should always work, unless you have a non SMP kernel which shouldn't be the case since at least 10 years :)
