### ISSUE TITLE
Separate burpui-agent to a new role

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_server#31]
Should I separate the burpui-agent to a new role?

I think it is good idea because of two benefits:

* Users that doesn't use this role (have their own way to install or use other system package, or just a developer that doesn't use it) could use the role to run burpui-agent too.
* Me and others could work in burpui-agent specific role, making it easier to develop upgrades for burpui and removing some code from this role to make this one smaller.

**Comment by pablodav** [comment]
what do you think @ziirish? @deajan ?

**Comment by ziirish** [comment]
Hello,

I think this is a good idea to put the bui-agent stuff into a dedicated role.
I actually did the same for did the same for burp-ui a couple of releases ago and there is now a dedicated pip package for both `burp-ui` and `bui-agent`.

**Comment by deajan** [comment]
Since burpui agents can be on different servers, it's indeed a good idea :)

**Comment by pablodav** [comment]
@ziirish , @deajan 

I think will remove supervisor as dependency for burpui-agent, instead will use the systemd unit provided in burpui-agent too.

If someone thinks it is a good idea to keep supervisor, will keep.

For other systems we could use SysV scripts?

**Comment by pablodav** [comment]
It's done, still need to update the Readme's docs before closing it.

**Comment by pablodav** [comment]
https://github.com/grke/burp/wiki/Automated-deploy-and-maintenance#ansible_burpui_agent
