### ISSUE TITLE
change address and port options in burp for next releases

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_server#32]
Thanks @grke for this message: 

A heads-up for you: In the next version of burp, the server-side 'address',
'port', 'status_address', and 'status_port' options are getting replaced
with: 'listen' and 'listen_status'.

These new options take the format '<ip address>:<port>'.
@grke,

**Comment by pablodav** [comment]
@grke 

so address and status_address will be removed?

**Comment by grke** [comment]
Yes.

**Comment by pablodav** [comment]
More comments from burp-users list:

 BREAKING change was
introduced in 2.2.10: the address/port and status_address/status_port have been
removed in favor of new unified "listen" and "listen_status" options.

Hello,

The setting that you get in the example server burp.conf.in file is:

listen = 0.0.0.0:4971

If you remove that, you get this, and the process exits with code 1:

**Comment by pablodav** [comment]
Sorry I'm late doing changes here, I'm was too overloaded of issues and challenges last months... I'm will try to get back into these issues soon.
