### ISSUE TITLE
change default paths in configuration 

### ISSUE THREAD

**Issue by pablodav** [CoffeeITWorks/ansible_burp2_server#34]
use more vanilla style config.

recommendation from @deajan, thanks you!

See it: https://github.com/CoffeeITWorks/ansible_burp2_server/commit/212a1468d98bf35a7133c28d76df712c622a1084#commitcomment-29982312

**Comment by pablodav** [comment]
I have prepared the changes in branch develop.

Will work for other features in this develop branch to not touch master until a release branch is tested with all features planned for next release are done.

In this way it gives me time to keep master (stable), develop, and a temporal release branch (like feature and refactor or hotfix branch), so there is nothing that breaks master until ready and I can also create any hotfix required to master without changing too much in master if needed. (gitflow workflow). 

There is still pending in this feature: 

* Test upgrades for current installations, as path changes I need to test current install and see how upgrade goes, probably will need to uninstall / install current installations like when I do upgrades, probably will not require any change but will require some test before closing.

ping @deajan

**Comment by deajan** [comment]
Sorry for the age long reply.
I am reinstalling a fresh burp server, and decided to give to go your path with ansible.
What do you need me to test here ?

**Comment by pablodav** [comment]
Hi @deajan,

Yes it is still valid, I haven't worked on this role last month and this one yet, will do on next one.

You can download / fork and clone this repo and use develop branch.

The vars are there to be changed in your own host_var or group_vars  directory/inventory.

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/develop/defaults/main.yml#L42

(Don't change them in the defauls/main.yml as it is only used by defaults, not for your own inventory/deploy).

You can use the role and see if it has all you need, or if there is something else required.

There are lot of customizations you can use, just see the default vars to see them.

**Comment by deajan** [comment]
I git cloned your repo, checkedout develop branch, copy it's contents over /etc/ansible/roles/CoffeeITWorks.burp2_server/ so far.
Now I was modiyfing defaults/main.yml, and you're telling me not to ? I don't get it.

**Comment by pablodav** [comment]
Yes, you should not modify it in the role itself.
https://github.com/CoffeeITWorks/ansible-generic-help

Your structure should be something similar to:

https://github.com/CoffeeITWorks/ansible-generic-help/tree/master/example1

So you have the roles/ dir with the role cloned there.
And modify the group_vars/group_burp2_server/burp2_server.yml

Or modify the host_vars/hostname.yml file

So you can modify the vars per group or server itself.

**Comment by pablodav** [comment]
You can have group_vars or host_vars dirs as subdir of inventory/ dir too (it could be better in today's structures).

**Comment by pablodav** [comment]
Now I have added better explanation here:

https://github.com/CoffeeITWorks/ansible-generic-help/#good-structure-of-files

**Comment by pablodav** [comment]
@deajan have you succeed previously?

I'm preparing many many new changes to support burp 2.2.10+ and other things in this role.

Will also add support for systemd before releasing
I have also split many parts like burp tests and burpui agent to another roles and performed many optimizations.
