### ISSUE TITLE
Syntax issue in burp_ca

### ISSUE THREAD

**Issue by marcin-github** [CoffeeITWorks/ansible_burp2_server#62]
Hi,
burp_ca provided by this role has error:
```*) if name="$(hostname -f)"; then ""; else name="$(hostname)"; fi ;;```

bash isn't happy when executes ` then ""`

**Comment by pablodav** [comment]
Thanks, seems an echo is missing there, strange it passed the tests.

**Comment by pablodav** [comment]
could you please confirm if this solved the issue for you?

**Comment by marcin-github** [comment]
This also works for me.
Gracias!
