### ISSUE TITLE
[usage question] - why incex inclusions/exclusions files are not copied to burp server?

### ISSUE THREAD

**Issue by marcin-github** [CoffeeITWorks/ansible_burp2_server#70]
Hi!
In file `profile_lnxsrv` are included files with inclusions and exclusions (like `audio_compressed_exclusions`) but there is no such files on server. Should I do set something in ansible variables to have this files copied to burp server?

**Comment by pablodav** [comment]
Could you show your tree in clientconfigdir?

I didn't get the point.

Here it's the one in a quick test:

```shell
root@ansibleburp2server-02:/# tree /etc/burp/clientconfdir/       
/etc/burp/clientconfdir/
|-- incexc
|   |-- profile_lnxsrv
|   |-- profile_lnxsrv_medium
|   |-- profile_win6x
|   |-- profile_win6x_drp
|   `-- profile_win6x_drp2
|-- monitor
`-- profiles
    |-- lnxsrv
    `-- win6x
```

These profiles comes from the var `profiles_templates`

You can check in [defaults/main.yml](https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/defaults/main.yml#L127) file.

**Comment by pablodav** [comment]
Sorry, I got the point....

You don't see /etc/burp/clientconfdir/incexc/audio_compressed_exclusions and others, checking....

**Comment by pablodav** [comment]
Seems it's a bug when I changed copy to synchronize here:

https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/tasks/4_config_burp.yml#L72

**Comment by marcin-github** [comment]
Thank you!
