### ISSUE TITLE
Role adds configuration to PowerTools repo but doesn't ensure the repository exists

### ISSUE THREAD

**Issue by guimaluf** [CoffeeITWorks/ansible_burp2_server#81]
I'm applying the role into a Centos 8 server and it is failing on the below task.

```
TASK [coffeeitworks.burp2_server : build-burp | install build dependencies] *******************
fatal: [burp-backup]: FAILED! => {
    "changed": false,
    "rc": 1,
    "results": []
}

MSG:

Cannot find a valid baseurl for repo: powertools
```
https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/tasks/1_2_redhat.yml#L21-L30

Although the role adds an entry to the PowerTools repository file it doesn't ensure there is an existing repository. Leading to the above failure.
```

# cat /etc/yum.repos.d/CentOS-Linux-PowerTools.repo                                                                                                                    

[powertools]
enabled = 1

```

**Comment by pablodav** [comment]
Thanks you for reporting this, I'm testing a possible fix.

Not sure why never got this issue during automatic tests.

See example:
https://github.com/CoffeeITWorks/ansible_burp2_server/runs/2699710925?check_suite_focus=true#step:4:209
